// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addFindingToPentest = `-- name: AddFindingToPentest :one
INSERT INTO findings (id, created_at, updated_at, title, status, severity, severity_score,
file, at_line, description, pentest_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, title, status, severity, severity_score, file, at_line, description, pentest_id
`

type AddFindingToPentestParams struct {
	Title         string
	Status        string
	Severity      string
	SeverityScore int32
	File          string
	AtLine        int32
	Description   string
	PentestID     uuid.UUID
}

func (q *Queries) AddFindingToPentest(ctx context.Context, arg AddFindingToPentestParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, addFindingToPentest,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.SeverityScore,
		arg.File,
		arg.AtLine,
		arg.Description,
		arg.PentestID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.SeverityScore,
		&i.File,
		&i.AtLine,
		&i.Description,
		&i.PentestID,
	)
	return i, err
}

const checkFindingAccess = `-- name: CheckFindingAccess :one
SELECT EXISTS (
    SELECT 1 FROM findings
    WHERE id = $1 AND pentest_id = $2
)
`

type CheckFindingAccessParams struct {
	ID        uuid.UUID
	PentestID uuid.UUID
}

func (q *Queries) CheckFindingAccess(ctx context.Context, arg CheckFindingAccessParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFindingAccess, arg.ID, arg.PentestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const closeFinding = `-- name: CloseFinding :exec
UPDATE findings
SET status = 'closed', updated_at = NOW()
WHERE id = $1 AND status != 'closed'
`

func (q *Queries) CloseFinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, closeFinding, id)
	return err
}

const getAllFindings = `-- name: GetAllFindings :many
SELECT id, created_at, updated_at, title, status, severity, severity_score, file, at_line, description, pentest_id FROM findings
`

func (q *Queries) GetAllFindings(ctx context.Context) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, getAllFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.SeverityScore,
			&i.File,
			&i.AtLine,
			&i.Description,
			&i.PentestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFindingsForPentest = `-- name: GetFindingsForPentest :many
SELECT id, created_at, updated_at, title, status, severity, severity_score, file, at_line, description, pentest_id FROM findings
WHERE pentest_id = $1
`

func (q *Queries) GetFindingsForPentest(ctx context.Context, pentestID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, getFindingsForPentest, pentestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.SeverityScore,
			&i.File,
			&i.AtLine,
			&i.Description,
			&i.PentestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wipeFindings = `-- name: WipeFindings :exec
DELETE FROM findings
`

func (q *Queries) WipeFindings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeFindings)
	return err
}
