// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Finding struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Status        string
	Severity      string
	SeverityScore int32
	File          string
	AtLine        int32
	Description   string
	PentestID     uuid.UUID
}

type Pentest struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	TeamID    uuid.UUID
}

type Team struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Teamname  string
}

type TeamMember struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	TeamID    uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Passwordhash string
}
