// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package database

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, created_at, updated_at, teamname)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, teamname
`

func (q *Queries) CreateTeam(ctx context.Context, teamname string) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, teamname)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Teamname,
	)
	return i, err
}
