// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (id, created_at, updated_at, user_id, team_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, user_id, team_id
`

type CreateTeamMemberParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, createTeamMember, arg.UserID, arg.TeamID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TeamID,
	)
	return i, err
}

const getAllTeamMember = `-- name: GetAllTeamMember :many
SELECT id, created_at, updated_at, user_id, team_id FROM team_members
`

func (q *Queries) GetAllTeamMember(ctx context.Context) ([]TeamMember, error) {
	rows, err := q.db.QueryContext(ctx, getAllTeamMember)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsForUser = `-- name: GetTeamsForUser :many
SELECT teams.id, teams.created_at, teams.updated_at, teams.teamname 
FROM teams
JOIN team_members ON teams.id = team_members.team_id
WHERE team_members.user_id = $1
`

func (q *Queries) GetTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Teamname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wipeTeamMember = `-- name: WipeTeamMember :exec
DELETE FROM team_members
`

func (q *Queries) WipeTeamMember(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeTeamMember)
	return err
}
